#!/bin/bash

#glance image-create --name chef2 --container-format bare --disk-format qcow2 --file /mnt/images/base_vm_local_chef.qcow2

#glance -d image-create --disk-format qcow2 --container-format bare --file keystone.qcow2  --name keystone-$BUILD_ID
glance -d image-create --disk-format qcow2 --container-format bare --file glance-api.qcow2  --name glance-$BUILD_ID

