#!/bin/bash
##
# Configure chef by looking at the metarepo service.

mkdir /etc/chef

CNF=/etc/chef/client.rb
cp -f $(dirname $0)/client.rb $CNF

CHEF_URL="http://blah.hpcloud.net"

## This seems wrong
sed "s/CHEF_URL/${CHEF_URL}" /etc/chef/client.rb

